### ISSUE TITLE
Number of BioSamples in in homepage does not match the updated database

### ISSUE THREAD

**Issue by ropolomx** [BeeBiome-consortium/beebiome-data-portal#21]
**Describe the bug**
The number of unique BioSamples doesn't match the number of entries in the updated database table. It is likely that this process is not automated, or if it is there might be another factor.

**To Reproduce**
1. Go to the homepage
2. Look at the number of BioSamples (unique entries). As of 2021-09-15 the number in the homepage is 10964,
3. Go to All data, then to Browse table. As of 2021-09-15 the number there is 11065.

**Expected behavior**
Number of unique BioSamples should match the number of entries in the table.

**Screenshots**

*Homepage*
![image](https://user-images.githubusercontent.com/7864897/133553516-447d0d9d-64b8-4691-9060-4f7459a9cc5a.png)

*Data table*
![image](https://user-images.githubusercontent.com/7864897/133553601-40214a9b-2ae2-4a0d-89ad-1179526879ac.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Edge
 - Version: 93.0.961.47 (Official build) (64-bit)

**Additional context**
The following files might be relevant, 

On the React side: [stats.js](https://github.com/BeeBiome-consortium/beebiome-data-portal/blob/816f0e211ff8d4c2d1a2f4b2eebc3f0bc14972d7/beebiome-web/src/components/home-page/stats/stats.js), in particular `this.state.data.sampleCount`

On the API side: [StatisticsResult.java](https://github.com/BeeBiome-consortium/beebiome-data-portal/blob/816f0e211ff8d4c2d1a2f4b2eebc3f0bc14972d7/beebiome-api/src/main/java/org/beebiome/dataportal/api/core/model/StatisticsResult.java), in particular `sampleCount`

Also on the API side: [ImportResult.java](https://github.com/BeeBiome-consortium/beebiome-data-portal/blob/08a0e291e0af8ba3f0efc2f583027ffeff476108/beebiome-api/src/main/java/org/beebiome/dataportal/api/core/model/ImportResult.java), in particular `sampleCount`

**Comment by vrechdelaval** [comment]
This is not an issue at all. 
You see 10964 BioSamples (unique entries) in home page stats because there are some BioSample linked to differents projects (e.g. SAMN14522241).
FYI, as you should have seen in `stats.js` and `StatisticsResult.java` and , statistics are updated automatically querying the db throw the API.

**Comment by ropolomx** [comment]
Thank you for clarifying that, @vrechdelaval !
